[package]
name = "wasmphobia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.4", features = ["derive"] }
gimli = "0.26.2"
inferno = { version = "0.11.19", default-features = false }
walrus = "0.20.3"
wasmparser = "0.206.0"
