[package]
name = "wasmphobia"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wasmphobia"
path = "src/main.rs"
doc = false

[profile.release]
debug = true
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
fallible-iterator = "0.2.0"
gimli = "0.26.2"
inferno = { version = "0.11.19", default-features = false, features = ["nameattr"] }
walrus = "0.20.3"
wasmparser = "0.206.0"
