[package]
name = "wasmphobia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.4", features = ["derive"] }
gimli = "0.26.2"
walrus = "0.20.3"
